- name: Install packaging tools
  ansible.builtin.apt:
    pkg:
      - dpkg-dev
      - dput
      - devscripts
      - fakeroot
      - lintian
      - quilt
      - debian-policy
      - git-buildpackage
      - pristine-tar
    state: present
