- name: Template wpa_supplicant
  ansible.builtin.template:
    src: 'templates/wpa_supplicant.conf.j2'
    dest: "/etc/wpa_supplicant-{{ network_wireless_iface[ansible_facts['hostname']] }}.conf_sample"
    mode: '0640'
    owner: root
    group: root
  tags: wpa_supplicant
