$ANSIBLE_VAULT;1.2;AES256;github
39326636326638323033376637363434316133323261393062313865383161613030316463386439
6364663838303938323666373961386663316461313936660a353062393331323633396138303433
66633134366439366364656339666134656662366261393731616237656430303931383164373736
6136366465613530320a666662383463656631313766663635613864396537633936333365313066
39363935623833356639363832313335316237336666353465663931336365383364636230613738
64623462613030363264383733306439366235663164323564616537303363323466323666623837
36386532393463363764326636636431323135326666646536393664396438323832356434326634
34366534366238613134653335623331346433396233316134383836396534306536363735336561
36636261303961633931366630323462393832323865396137313033376134313838366564333631
30316561633165326635396133326364633533663235373761616363373461326664666464353139
31356337643763643164306565333462313663373839303833616166643636316134626464376166
36653830373835616561363239653336643137323839356433643535313565663434313830393033
39653630333030633430623130326266306365613266663664623338373338333762633934633766
39313763313163633332316433643633636433346630353662343661666538343764333336383133
32663463363866373638626537396132613632373330333733313033303566303666316338376436
65623735393266316366613331353538633462636462643664643737633164616131616130343064
39396464396165353566613736323461613736663066643734346239333837393563383663643638
31326462303032666334663833333631323335373732636462333665396139393734656536343039
36333762316233323836346530373032303739666232333062383034356631363966353662356665
30333831313964663136653533653032616534653437623230643965343437636436396231396266
61643232313461623166343163633433306136646464663334353766616532356333393566643031
61636537353865646663333335363931343561316363633861303537666637636466313665396266
32623432363565326330326639616438346136393839373432666234333561636536663836613637
62316139316263626364366533333965366134323336616639346130623062623832663766313736
62653136656431356366663162343063316131633232653630633864366165393163383238646536
61366364623264393265646432646561616630666165656462346133633534303531366265383765
61643663356262393861333333306266393663343536663662366231336235646439356133363137
35613633326532373937346233303561643062613765333166646662326465626233656166313539
63623766613136326264663638396535666338386435323434333862343534306532343131626635
38626631326534376631376639386436663263306637653763336335393435313836666633623963
32363361613162656338633664646162343531356561653930373932303564386235306563353062
62376366343035653461353732363634356134393233383336363931363430666232356562376535
34353530313861376434613330373461333865353262363963333530616565396562643838363566
39653032616364653937353738343035316562646634333264393631363661653733623433303664
30626137333434373133333232356334373661326165633962653932366233616630326531383637
64366533366362646236663366366436653961383134356166626663313134323536666462373761
33643931383534613865326463663431636431353765373363303732336565303963353935313634
35313038613139626231386538363162613736663063623662303232633864633735386231306236
61343139396461353134653862616139383764363363663462356364383766653137633738303464
64663730396363363637616633353138396334653936366637626461626634346361643632393934
66356539643634343266393537313339633039336233313861306634656462656631633430333133
64623532356165323962343635353933633064633964373865663533323238393136356437343536
30646462346464666561366565333836663165646436376632656166323630376436373931376263
32643632316662653139343034316661363766616439396437646566643465306630656630613665
35323333366534346131656235386462316335323865376337323931393162356634613433376536
30653935653230663932636632623836386237333030373165393465633761396137356535646164
64396134613861383864613537613137376638323266623435356632383966663634373437393131
34363361323037613837643264373530656562356235313935653333643538376635623939333237
66653561333135316535316661346634376334373130386438653932303733393931383937313035
61643432386164353764653664353237623337393632326637313361343832616632326234353566
32363365626135326264333964303637353730643332333137363737383139643662626163373566
37343963373034353530336465313538663331666166383531626464396561626234303337326264
30353731633438623336343666646631383835366364656134626163323632306565
